apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ohorizons-tasks-api-mvp-secrets
  namespace: ohorizons-tasks-api-mvp
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openhorizons-dev-secret-store
  target:
    name: ohorizons-tasks-api-mvp-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: tasksdb-connection-string
