apiVersion: v1
kind: Service
metadata:
  name: ohorizons-tasks-api-mvp
  namespace: ohorizons-tasks-api-mvp
  labels:
    app: ohorizons-tasks-api-mvp
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ohorizons-tasks-api-mvp
