name: Despliegue ACR SURA
on:
 push:
   branches:
     - main
     - develop
env:
 ACR_NAME: crsuradev
 REGISTRY: crsuradev.azurecr.io
 IMAGE_NAME: ohorizons-tasks-api-prueba
 SUBSCRIPTION_ID: f0550323-fb0b-44d4-8a39-ecf0f6c2dbc9
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - name: Azure Login
       run: |
         az login
           --device
           --tenantId "9dbc76ea-fb25-4b07-8f07-5dc315999b76"
     - name: Select Subscription
       run: |
         az account set
           --subscription $SUBSCRIPTION_ID
     - name: Login to ACR
       run: |
         az acr login --name $ACR_NAME
     - name: Build Image
       run: |
         docker build
           -t $REGISTRY/$IMAGE_NAME:latest
           -t $REGISTRY/$IMAGE_NAME:${GITHUB_SHA}
           .
     - name: Push Image
       run: |
         docker push $REGISTRY/$IMAGE_NAME:latest
         docker push $REGISTRY/$IMAGE_NAME:${GITHUB_SHA}